### ISSUE TITLE
GTK scaling issues on Steam Deck OLED

### ISSUE THREAD

**Issue by aclist** [aclist/dztui#137]
A user reports that certain modal dialogs appear scaled grossly out of proportion on Steam Deck OLED, notably on Game Mode. This is a variant of a GTK bug previously reported to Valve.

However, the user demonstrated (with visual proof) that the modals also get resized in Desktop Mode beyond the dimensions of the viewport.

Finally, the application itself seems to extend beyond the confines of the viewport for no discernible reason.

Lacking a Steam Deck OLED test bench, as an initial test, asked the user to try a modified version of the UI which disables window hinting and maximize parameters. Going forward, it may be best practice to not start DZGUI in fullscreen/maximized, but need to test the implications of this on Game Mode, due to its tendency to throw windows into the wrong place.

**Comment by jiriks74** [comment]
> Finally, the application itself seems to extend beyond the confines of the viewport for no discernible reason.

I was just about to report this. It happens consistently on my laptop so if you'd like some testing feel free to contact me.

> [!Important]
> I happens with `Server browser`, `My servers` and `Recent servers`. If that's the case for this issue I'd guess that it has to do something with the amount of columns/horizontal data as it doesn't happen in any other menu/list (`List installed mods`).
> 
> The window can be resized to a smaller size again when I go back to any menu not showing any server list.

When I recorded the behavior (see below) I noticed that the app resizes after the server list is loaded. You can see all the columns with the window staying the same size while the server list is loading and then it resizes to a size bigger than my screen once the servers are loaded.

With this kind of behavior it might have to do something with the server names as they're way longer than any other text shown (most of the time). I haven't done much UI, let alone in GTK, but it looks like that everything is anchored to the right so the `Name` column extends to the left.

> [!Tip]
> I've seen that there should be something like a scrollable widget in GTK so it may help to nest the main view into that?

<details>
<summary>Recording</summary>

[Screencast_20241129_003329.webm](https://github.com/user-attachments/assets/02796096-bc1b-44a5-a086-dc510c411fcf)

</details>

> [!Note]
> What you see when I move the windows and it gets maximized is Krohnkite. It's a tiling extension and I've set it to Monocle (aka make the focused window take the whole screen).
>
> The movement of the window triggers Krohnkite again and it resizes the window to the full screen again.

**Comment by jiriks74** [comment]
> But for tiling WMs (e.g. i3wm), you might have to explicitly tell the WM in its conf files that DZGUI is a floating window application and shouldn't be maximized.

Well, that's the thing it does this in floating mode as well. I, most of the time switch DZGUI to floating mode so that when it gets bigger than my screen I can actually move it to the right to see the server name.

> The issue above is that gamescope on Steam Deck Gaming Mode seems to try to force things that should be dialogs into fullscreen

So basically what a tiling WM does but Krohnkite tries to detect popups and doesn't resize them. The second thing as I mentioned above is that the same thing happens in floating mode. 

> [!Important]
> Now that I think of it, it may be related to my screen setup. My laptop's screen is 16 :10, not 16 :9 like my desktop and most other setups, 1440p screen. I also have it set to 150% scaling.

**Comment by aclist** [comment]
@jiriks74 

I'm ready to revisit this issue now. Are you still experiencing it on your laptop with the latest version?

**Comment by jiriks74** [comment]
Hi,
I'll look later today. Hopefully it won't be a complicated issue.

**Comment by jiriks74** [comment]
Sorry for the delay.

I just checked and I can still reproduce the issue.

**Comment by aclist** [comment]
Alright, I'll start picking this apart for the [5.7.0](https://github.com/aclist/dztui/milestone/6) milestone.

This is probably having a related effect on Steam Deck.

**Comment by aclist** [comment]
@jiriks74 Could you give me some additional info about the laptop's logical resolution and the physical size of the display (e.g. 13'')?

**Comment by jiriks74** [comment]
The display is a 17" 16:10 1440p 120Hz 2560x1600 panel. I run it at 150% scaling.

<details>
<summary>Screenshow of KDE Plasma settings</summary>

![image](https://github.com/user-attachments/assets/fc4aa92a-3e26-4cd5-9d77-d0c581ec9795)

</details>

**Comment by aclist** [comment]
@jiriks74 Can you try the following?

- Suppress creation of right panel when server browser loads
Comment out line `1447` of `$HOME/.local/share/dzgui/helpers/ui.py`:
`#right_panel.set_filter_visibility(True)`

- Suppress auto-update of UI files in `dzgui.sh`
Comment out line `943` of `dzgui.sh`:
`#fetch_helpers > >(pdialog "Checking helper files")`

**Comment by jiriks74** [comment]
I'll try looking into it tomorrow.

**Comment by gabrieled07** [comment]
Hi, I was about to post the same issue, I'm using:
Ubuntu 22.04.1
Python 3.10.12
amdgpu, with 3 monitors, 2 same size, 1 little extra resolution


In my case, the line to comment is 1445, 
This change fixes the resizing issue in all menu items
even opening in monitor B, full screen, moving to A and choosing another menu

Hope that helps, tell me if you need more info or to try other things, and thanks for your work!

Gabriel

**Comment by aclist** [comment]
> Hi, I was about to post the same issue, I'm using: Ubuntu 22.04.1 Python 3.10.12 amdgpu, with 3 monitors, 2 same size, 1 little extra resolution
> 
> In my case, the line to comment is 1445, This change fixes the resizing issue in all menu items even opening in monitor B, full screen, moving to A and choosing another menu
> 
> Hope that helps, tell me if you need more info or to try other things, and thanks for your work!
> 
> Gabriel
> 
> Edit: DZGUI version is 5.6.5

Thanks for the additional data point and feedback. You are talking about https://github.com/aclist/dztui/blob/dzgui/helpers/ui.py#L1445, correct? This is really helpful information and gives me something more concrete to go on. If that's the case, then the filter panel isn't being inserted correctly into the grid or is falling outside of the constraints of the normal grid. When it gets enabled, it shouldn't be pushing the entire window offscreen, as the window should have a constant size.

I'll investigate fixing this so that you don't have to disable the entire right panel.

The line you commented willl not affect `Options > List installed mods`, however. Do you still have the irregular resizing issue in that area?

**Comment by gabrieled07** [comment]
Yes, the line is the one you just mentioned. [(https://github.com/aclist/dztui/blob/dzgui/helpers/ui.py#L1445)]


Installed mods is not affected by the issue, even re-enabling the commented line,
and to confirm,
leaving the line uncommented causes the resizing issue again

Python or gkt are not my thing, but if you need more testing, please tell me

Perhaps the problem came from the server list box, you can resize up to a point, way out of screen size

**Comment by aclist** [comment]
Thank you. I am thinking about it. I have some ideas about suppressing the hexpand (horizontal expand) property of this widget. Unfortunately, I haven't found the magic combination of right resolution and window manager that causes this behavior (going outside of the screen).

On all of my setups, it is constrained to the display, so I haven't found a good way of reproducibly triggering this behavior, even thought it clearly exists. Can you tell me what resolution and window manager you're using? Once I can physically recreate this problem, it'll be easy to solve. (I don't want to keep asking you to test small changes.)

**Comment by aclist** [comment]
> Perhaps the problem came from the server list box, you can resize up to a point, way out of screen size

And thanks for that tidbit, will take a look.

**Comment by aclist** [comment]
@gabrieled07 

I used some artifically low resolutions and started to see the behavior.
Might have something for you: can you uncomment line 1445 again and add this to line 898?

`self.set_hexpand(False)`


Before:
```
class ScrollableTree(Gtk.ScrolledWindow):
    def __init__(self, is_steam_deck):
        super().__init__()

        self.treeview = TreeView(is_steam_deck)
        self.add(self.treeview)
```

After:
```
class ScrollableTree(Gtk.ScrolledWindow):
    def __init__(self, is_steam_deck):
        super().__init__()

        self.treeview = TreeView(is_steam_deck)
        self.add(self.treeview)
        self.set_hexpand(False)
```

**Comment by gabrieled07** [comment]
That code didn't work, but i've tried this:
`class ScrollableTree(Gtk.ScrolledWindow):
    def __init__(self, is_steam_deck):
        super().__init__()

        self.treeview = TreeView(is_steam_deck)
        self.set_hexpand(False)
        self.add(self.treeview)`
(set the property before adding the thing)

My saved servers, recent and installed mods works as it should
Server browser has the expanding size issue 

I've been testing a little, Qport on server browser expands a lot when the thing goes out of screen, you cant shrink it or resize it. AND if you expand that column on the views that work, the menu again goes out of screen. 
Maybe it can be forced to a size?
Perhaps one of the servers reports a very long port and breaks the menu?

I'm using gnome 
and i have:
(1) 1600x900 and (2),(3) 1366x768

**Comment by aclist** [comment]
> (set the property before adding the thing)

This shouldn't matter, as the property can be set after the fact. At the time this widget is added, the table is just initialized but empty.

> My saved servers, recent and installed mods works as it should. Server browser has the expanding size issue
> Perhaps one of the servers reports a very long port and breaks the menu?

I think the fix actually worked, but due to user preferences for column widths being saved, it was reverting to the larger column width.

Go to `$HOME/.local/state/dzgui`, open `dzg.cols.json`, and change the `Qport` value to a sane one like 100. It's probably abnormally large right now. This value represents the width in pixels. Alternatively, backup and remove the file entirely and check the result. This file contains the user's preference for resizable column widths.

What likely happened is that the expand property caused the last field to take up all available space, and this was saved in the state file as the last known column preference, so subsequent attempts to reopen the table keep forcing the column to this abnormal size, as though it was a preference set by the user.

Snippet from the GTK documentation, my bolded text:

> Sets the column to take available extra space. This space is shared equally amongst all columns that have the expand set to True. **If no column has this option set, then the last column gets all extra space**. By default, every column is created with this False.

> Perhaps one of the servers reports a very long port and breaks the menu?

All rows were no more than 5 digits long, no extra padding. Query port is one area it's impossible for server operators to add extra metadata into it, so it always comes back well-formed, unlike server names, which can contain anything under the sun.

**Comment by gabrieled07** [comment]
Ok, done and tried a few things:

> dzg.cols.json
Qport width was +600, changed that but no effect,
deleted the json and it was recreated with:

`{
  "cols": {
    "Name": 800,
    "Map": 300,
    "Perspective": 115,
    "Gametime": 104,
    "Players": 83,
    "Maximum": 99,
    "Queue": 79,
    "IP": 152,
    "Qport": 73
  }
`
expanding the menu out of screen,

I've added the following to lines #1598 at ui.py

`if ("Name" in column_title):
                    column.set_fixed_width(350)
                if (column_title == "Map"):
                    column.set_fixed_width(150)
                if (column_title == "Perspective"):
                    column.set_fixed_width(50)
                if (column_title == "Gametime"):
                    column.set_fixed_width(50)
                if (column_title == "Players"):
                    column.set_fixed_width(80)
                if (column_title == "Maximum"):
                    column.set_fixed_width(50)
                if (column_title == "Queue"):
                    column.set_fixed_width(50)
                if (column_title == "IP"):
                    column.set_fixed_width(100)
                if (column_title == "Qport"):
                    column.set_fixed_width(100)
`

and the dzg.cols.json is recreated with this settings:

`{
  "cols": {
    "Name": 350,
    "Map": 150,
    "Perspective": 50,
    "Gametime": 50,
    "Players": 80,
    "Maximum": 50,
    "Queue": 50,
    "IP": 100,
    "Qport": 681
  }`

The Qport column or the total size of the grid comes from another place, out of my python/gtk reach, but maybe can be implemented something like getting screen width and calculating the columns?
like:
`GdkRectangle workarea = {0};
gdk_monitor_get_workarea(
    gdk_display_get_primary_monitor(gdk_display_get_default()),    &workarea);`


Another behavior, when you browse on recent servers, for example, and try to connect (at this point the menu is fine within the screen) double-clicking it resizes the menu out of screen

**Comment by aclist** [comment]
Thanks for your help and patience.

I actually missed a spot where the hexpand property was getting reverted despite the changes suggested above. It looks like a behavior to restrict the table size was already in place for Steam Deck, but for some reason it was being allowed to apply for desktop PCs:

https://github.com/aclist/dztui/blob/f75ef947c93d3f3ce918c5d8ed7043e5a34999bf/helpers/ui.py#L2333

Remove this conditional check for Steam Deck and change it so that the methods are uniformly applied in all contexts:

```
self.scrollable_treelist.set_hexpand(False)
self.scrollable_treelist.set_vexpand(True)
```

You can also try disabling line 2331, although this may have side effects on the appearance of the main menu.

> The Qport column or the total size of the grid comes from another place, out of my python/gtk reach, but maybe can be implemented something like getting screen width and calculating the columns?
like

It's true that the window resizing logic is a naive implementation and is mostly delegated to GTK's defaults, which work *most* of the time. I think this is a separate problem separate from the grid/table issue, though. For example, the main menu itself can simply be too big at low resolutions . I forced a scaled resolution of 1366x768 on a 1440p monitor as a test, and the application starts beyond the edge of the screen. By contrast, generic applications like a web browser will scale to fit all contents even if the resolution is low.

> Another behavior, when you browse on recent servers, for example, and try to connect (at this point the menu is fine within the screen) double-clicking it resizes the menu out of screen

Not sure of the root cause of this yet.

I'm sorry we haven't gotten a definitive fix yet, but you've made some good deductions that are putting us in the right direction. GTK is a wild beast to tame at the best of times.

**Comment by aclist** [comment]
Here's a drop-in replacement for `ui.py` you can try that applies a few changes: https://raw.githubusercontent.com/aclist/dztui/refs/heads/chore/test-ui/helpers/ui.py

- Set expand property to `False`
- Allocate fewer grid columns to table
- Calculate size of root screen and attempt to set maximum size request

I also need to look into creating more columns for the filter labels, because currently they just expand vertically instead of being arrayed in a grid, and this takes up too much space when the filter panel isn't active.

**Comment by gabrieled07** [comment]
I've tried https://raw.githubusercontent.com/aclist/dztui/refs/heads/chore/test-ui/helpers/ui.py

It works as it should on every menu, no more out of screen resizing, even when double-clicking on a server, on browser and saved menus
There are some minor things, if you want to be a perfectionist, like maximizing only works on main menu, the size or status (maximized) its not remembered, and some very minor details.
As it is, its much more comfortable to use

> Thanks for your help and patience

Hey, I've been using your app for quite some time, the least I can do is help you a little to improve it
Thank you for putting the time to develop ways to shoot people from linux!

**Comment by aclist** [comment]
> It works as it should on every menu, no more out of screen resizing, even when double-clicking on a server, on browser and saved menus

Thanks for confirming. I'll clean up some things and merge this into the testing branch soon, then into the stable branch after a while.

>  maximizing only works on main menu

Hmm, I'll look into that. It could be a WM limitation.

> the size or status (maximized) its not remembered

Take a look at `Options > Toggle DZGUI fullscreen boot`. This makes the fullscreen option persistent if you wish. It used to be the default to fullscreen, which also removes all  of the resizing problems, but people stated that they wanted to be able to not fullscreen, so it's optional now.

As for the size and position, I think it's best to delegate it to the window manager itself. (If the window manager refuses to remember the position of only this app, that's a new problem.) It could be saved in the application, but it introduces a lot of potential gotchas and a lot more weird screen calculations that have to be done.

I'm not fully satisfied with the look of the main menu after this fix, because it looks very long (vertical), so I think I'll try to compress some of the right options into more of a flowed grid.

**Comment by jiriks74** [comment]
Hey there.
Sorry for disappearing. Things happened and this got buried in my inbox so I forgot about it.

I can't do testing as of now because the device this happened on is under RMA (again...). I'm glad that someone else was able to do testing for you and that you were able to reproduce this.

I'll see whether they'll give me the device or my money back. If I get the device I could do some more testing for you.

**Comment by aclist** [comment]
@jiriks74 

No worries, DZGUI will be here waiting for you when you return. I think we are closing in on resolving this resolution bug once and for all.

@gabrieled07

There's a new alpha version (out-of-branch) of the UI you can grab here https://raw.githubusercontent.com/aclist/dztui/refs/heads/chore/test-ui/helpers/ui.py and drop in as a replacement. 

- Arranged filter checkboxes into a grid so that it takes up less space
- Tries to remember the last size of the application on quit. When restarting the app, this size will be restored, provided the requested X/Y size is at least larger than the space DZGUI needs to set up its UI elements at startup.
- If the application is maximized when you quit, the fullscreen size will not be saved as the last known size; the size before it was maximized will be retained.
- If the requested size could not be set, DZGUI will revert to the default size.

**Comment by gabrieled07** [comment]
Cool! I'll try it and report back
Thanks!

**Comment by gabrieled07** [comment]
A little faster than I thought, because I was ready to 'use'  dzgui ;)

if` .local/state/dzgui/dzg.res.json` is not present (my case when first launched the last alpha)
the following error is reported:

```
Traceback (most recent call last):
  File "/home/griera/.local/share/dzgui/helpers/ui.py", line 2847, in <module>
    main()
  File "/home/griera/.local/share/dzgui/helpers/ui.py", line 2843, in main
    App()
  File "/home/griera/.local/share/dzgui/helpers/ui.py", line 2449, in __init__
    self.win = OuterWindow(is_steam_deck, is_game_mode)
  File "/home/griera/.local/share/dzgui/helpers/ui.py", line 891, in __init__
    if valid_json:
UnboundLocalError: local variable 'valid_json' referenced before assignment
Terminated
```
I've created the file empty, the app starts and works ok (will try it better and report back)
Then the size info is stored:

```
{
  "res": {
    "width": 1184,
    "height": 777
  }
}
```

and next start does not produce any errors

Hope that helps

Gabriel

**Comment by aclist** [comment]
Thanks. I've fixed the control flow a bit here: https://raw.githubusercontent.com/aclist/dztui/22758938bd40bf6e5bd5b3eba2fe03db7625133c/helpers/ui.py

There were a few other issues, such as fullscreen mode blocking quit signals.

This should be mostly stable now. I am going to test this on Steam Deck before merging into the testing branch.

**Comment by gabrieled07** [comment]
Hi, I've tested the last one, and I'm not finding anything to complain about ;)

Works great, maximize behavior is as expected on every sub-menu
`dzg.res.json` is created if it's not present, it starts and recreate the directory `.local/state/dzgui` and its contents if its missing     
When connecting to servers, screen doesn't change position or size
Grid resized columns are remembered correctly

**Comment by aclist** [comment]
Thank you very much for testing. I've merged these UI changes into the `Testing` branch. You can uncomment line `943` of `dzgui.sh` in order to start pulling in updates again. To access the testing branch, navigate to `Options > Toggle release branch` if you aren't on that branch already.

If there are no issues, in a few days, these changes will be merged into the `Stable` branch (default DZGUI branch).

**Comment by aclist** [comment]
This has now been merged into the stable branch, so I'm closing this ticket. I might ask for your help again in the future with beta testing some things.
